INSERT INTO Categoria(ID_Categoria,Nombre) VALUES
 (1,'pulvinar arcu et')
,(2,'ornare, libero at')
,(3,'lacus. Quisque imperdiet,')
,(4,'tempor diam')
,(5,'sem, vitae')
,(6,'Nunc ullamcorper, velit in')
,(7,'In mi pede,')
,(8,'Proin dolor. Nulla')
,(9,'sollicitudin a,')
,(10,'blandit. Nam nulla')
,(11,'mollis')
,(12,'dolor sit amet,')
,(13,'arcu vel quam dignissim')
,(14,'eu nibh')
,(15,'consequat purus. Maecenas')
,(16,'Suspendisse eleifend. Cras sed leo.')
,(17,'accumsan convallis,')
,(18,'vehicula aliquet libero. Integer in')
,(19,'bibendum fermentum metus. Aenean')
,(20,'magnis dis')
,(21,'condimentum. Donec')
,(22,'netus')
,(23,'Quisque ac libero nec ligula')
,(24,'purus ac tellus. Suspendisse')
,(25,'sollicitudin commodo')
,(26,'Cum sociis')
,(27,'sollicitudin adipiscing ligula.')
,(28,'sed dolor.')
,(29,'Quisque ornare tortor')
,(30,'Nulla tincidunt,')
,(31,'nec mauris blandit')
,(32,'elit sed consequat auctor, nunc')
,(33,'ante ipsum')
,(34,'metus facilisis lorem')
,(35,'bibendum. Donec')
,(36,'neque non quam. Pellentesque')
,(37,'placerat. Cras dictum')
,(38,'adipiscing lacus. Ut nec')
,(39,'nisi. Mauris nulla. Integer')
,(40,'dolor dapibus gravida. Aliquam')
,(41,'risus. In')
,(42,'et magnis dis parturient')
,(43,'Mauris quis turpis vitae')
,(44,'mauris erat')
,(45,'dictum cursus. Nunc mauris elit,')
,(46,'Donec non justo. Proin non')
,(47,'ipsum dolor sit')
,(48,'ac orci. Ut')
,(49,'pede. Cras')
,(50,'Ut sagittis lobortis mauris.');